---
date: "Report Date: `r Sys.Date()`"
author: "NYSDEC SMAS"
title: "Stream Survey Data Report"
output:
  officedown::rdocx_document:
    reference_docx: draft_template.docx
    tables:
      style: Table
      layout: 'autofit'
      width: 0.75
      caption:
        style: Table Caption
        pre: 'Table '
        sep: '. '
    plots:
      style: Normal
      align: center
      caption:
        style: Image Caption
        pre: 'Figure '
        sep: '. '
        fp_text: '`officer::fp_text_lite(bold = FALSE)`'
params:
    tox: FALSE
    bap: TRUE
    habitat: TRUE
    study_name: "Finger Lakes Advanced Stream Monitoring"
    year_input: 2017
    intro_file_name: "intro.csv"
    sites_file_name: "sites_fl_good.csv"
    grouping_for_chem: site
    grouping_for_bap: site
    map_zoom: 12
    user: kareynol
    limit_to_nuts: TRUE
    data_package: FALSE
    lit_cited_file: "lit_cited.docx"
    map_file: "fl_map.png"
     
---

```{r setup, include=FALSE,eval.expr=TRUE}
knitr::opts_chunk$set(echo = FALSE, fig.cap = TRUE)
library(officedown)
library(officer)

fp <- fp_par(
  text.align = "center", 
  padding.bottom = 20, padding.top = 120, 
  border.bottom = fp_border())

fp_text(shading.color='#EFEFEF', bold = FALSE)

study_name=params$study_name
tox=params$tox
bap=params$bap
habitat=params$habitat
intro_file_name=params$intro_file_name
sites_file_name=params$sites_file_name
year.input=params$year_input
#updated_sites_file_name=params$updated_sites_file_name
grouping_for_bap=params$grouping_for_bap
grouping_for_chem=params$grouping_for_chem
map_zoom=params$map_zoom
user=params$user
limit_to_nuts=params$limit_to_nuts
data_package=params$data_package
lit_cited_file=params$lit_cited_file
map_file=params$map_file

knitr::opts_chunk$set(tab.topcaption = TRUE)
knitr::opts_chunk$set(fp_text_lite(bold = FALSE))

  
```


```{r message=FALSE,warning=FALSE,echo=FALSE}

year_input=params$year_input
source(here::here("rmd/r_scripts_raw/stayCALM_exceedances_updated.R"))
source(here::here("rmd/r_scripts_raw/functions.R"))
source(here::here("rmd/r_scripts_raw/preprocessing_1_raw_updated_1_11_21.R"))
year.input=params$year_input
source(here::here("rmd/r_scripts_raw/preprocessing_2_chemistry.R"))
if (params$bap) {source(here::here("rmd/r_scripts_raw/preprocessing_3_bap.R"))}
if (params$habitat) {source(here::here("rmd/r_scripts_raw/preprocessing_4_habitat.R"))}
source(here::here("rmd/r_scripts_raw/preprocessing_5_user_perception.R"))
source(here::here("rmd/r_scripts_raw/preprocessing_6_tox.R"))
source(here::here("rmd/r_scripts_raw/appendices_and_data_package.R"))
source(here::here("rmd/r_scripts_raw/preprocessing_7_sect_2.R"))

```

<!---CHUNK_PAGEBREAK--->

<!---BLOCK_TOC--->

<!---CHUNK_PAGEBREAK--->


# General
```{r child="child/section1_General.Rmd"}

```
\newpage

# Section I: Overview

```{r child=if(params$bap)"child/section1B_BAP.Rmd"}}
if(bap){cat("# Benthic Macroinvertebrate Community")}

```

## Water Quality
```{r child="child/section1A_chemistry_stream_discharge.Rmd"}

```

```{r child=if(params$habitat)"child/section1C_stream_reach_phys.Rmd"}}
if(habitat){cat("# Stream Reach Physical Habitat Characteristics")}

```

## User Perception
```{r child="child/section1D_User_Perception.Rmd"}

```


```{r child="child/section1E_tox.Rmd"}

if(params$tox){cat("# Sediment and Porewater Microtox® Analysis")}
```
\newpage
# Section II: Site Specific Data
```{r child="child/section_2_short.Rmd"}
#child="child/section_2_short.Rmd"
```
\newpage

# Section III: Literature Cited

```{r appendices, echo=FALSE, warning=FALSE, message=FALSE}
block_pour_docx(file = here::here(paste("data",lit_cited_file,sep ="/")))
```

\newpage
# Section IV: Appendices

```{r child="child/appendices.Rmd"}

```

